# Generated by Django 3.2.24 on 2024-03-03 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_item_done'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='done',
        ),
        migrations.AddField(
            model_name='item',
            name='description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
