# Generated by Django 3.2.24 on 2024-04-15 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_product_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
