# Generated by Django 3.2.24 on 2024-04-27 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item',
            field=models.CharField(default='default_value_here', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='item_detail_1',
            field=models.CharField(blank=True, default='default_value_here', max_length=255),
        ),
        migrations.AddField(
            model_name='product',
            name='item_detail_2',
            field=models.CharField(blank=True, default='default_value_here', max_length=255),
        ),
    ]
